WITH QUERYSTATS AS (
    SELECT 
        QUERY_NAME,
        COUNT(*) AS TOTAL_QUERIES,
        COUNT(CASE WHEN RATING < 3 THEN 1 END) AS POOR_QUERIES,
        AVG(RATING / POSITION) AS AVG_QUALITY
    FROM QUERIES
    WHERE QUERY_NAME IS NOT NULL
    GROUP BY QUERY_NAME
)

SELECT 
    QUERY_NAME AS query_name,
    ROUND(AVG_QUALITY, 2) AS quality,
    ROUND((POOR_QUERIES * 100 / TOTAL_QUERIES), 2) AS poor_query_percentage
FROM QUERYSTATS;

-- OR--
SELECT QUERY_NAME as query_name, 
ROUND(AVG(RATING/POSITION), 2) AS quality, 
ROUND(((SELECT COUNT(*) FROM QUERIES WHERE QUERY_NAME=Q1.QUERY_NAME AND RATING < 3) / (SELECT COUNT(*) FROM QUERIES WHERE QUERY_NAME=Q1.QUERY_NAME)) * 100, 2) AS poor_query_percentage
FROM QUERIES Q1
WHERE Q1.QUERY_NAME IS NOT NULL
GROUP BY Q1.QUERY_NAME
;
