SELECT R.CONTEST_ID AS contest_id,
ROUND((COUNT(R.CONTEST_ID)/(SELECT COUNT(*) FROM USERS)) * 100, 2) AS percentage
FROM REGISTER R
JOIN USERS U ON U.USER_ID = R.USER_ID
GROUP BY R.CONTEST_ID
ORDER BY percentage DESC, R.CONTEST_ID ASC; 
